const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{
 const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,headless:true}),ctx=await browser.newContext({viewport:{width:390,height:844},hasTouch:true}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{const get=k=>sessionStorage.getItem('native:'+k),put=(k,v)=>{sessionStorage.setItem('native:'+k,v);return true;};window.AndroidStudy={get,put,drop:()=>true,hasKey:()=>true,ai:(id,payload)=>{window.lastRequest={id,payload:JSON.parse(payload)};StudyBridgeEvent({id,type:'delta',content:'先考虑条件概率，不要急着套公式。'});},cancel:()=>{}};});
 await p.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
 await p.locator('#question-ask-ai').click();assert.equal(await p.locator('body').getAttribute('data-chat-sheet'),'true');assert.equal(await p.locator('#ai-bank-root').isVisible(),true);
 const box=await p.locator('#study-dialog').boundingBox();assert.ok(box.height<=340);const inputBox=await p.locator('#study-input').boundingBox(),quizBox=await p.locator('#ai-bank-root').boundingBox();assert.ok(inputBox.y-box.y<80);assert.ok(quizBox.y+quizBox.height<=box.y+1);
 const startScroll=await p.locator('#ai-bank-root').evaluate(el=>el.scrollTop),cdp=await ctx.newCDPSession(p);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:190,y:320}]});for(const y of [280,230,180,130])await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:190,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await p.locator('#ai-bank-root').evaluate(el=>el.scrollTop)>startScroll);
 await p.locator('#study-input').fill('未发送的第一题问题');
 const dragHandle=async delta=>{const h=await p.locator('#study-sheet-handle').boundingBox(),x=h.x+h.width/2,y=h.y+12;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=6;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y+delta*i/6}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});};
 const beforeDrag=(await p.locator('#study-dialog').boundingBox()).height;await dragHandle(-100);assert.ok((await p.locator('#study-dialog').boundingBox()).height>beforeDrag+80);await dragHandle(100);assert.ok(Math.abs((await p.locator('#study-dialog').boundingBox()).height-beforeDrag)<5);await dragHandle(beforeDrag-120);assert.equal(await p.locator('#study-dialog').isVisible(),false);await p.locator('#question-ask-ai').click();assert.equal(await p.locator('#study-input').inputValue(),'未发送的第一题问题');
 await p.locator('#study-chat-size').click();assert.equal(await p.locator('body').getAttribute('data-chat-sheet'),'false');assert.equal(await p.locator('#ai-bank-root').isVisible(),false);assert.equal(await p.locator('#study-input').inputValue(),'未发送的第一题问题');await p.locator('#study-chat-size').click();await p.locator('#study-chat-hide').click();assert.equal(await p.locator('#study-dialog').isVisible(),false);
 await p.locator('#question-ask-ai').click();assert.equal(await p.locator('#study-input').inputValue(),'未发送的第一题问题');await p.locator('#study-send').click();const first=await p.evaluate(()=>window.lastRequest.id);await p.locator('#study-chat-hide').click();await p.evaluate(id=>{StudyBridgeEvent({id,type:'delta',content:'收起后仍继续保存。'});StudyBridgeEvent({id,type:'done'});},first);await p.locator('#question-ask-ai').click();assert.match(await p.locator('#study-messages').innerText(),/收起后仍继续保存/);
 await p.locator('#study-input').fill('第一题追问草稿');
 // A background question change must switch the sheet to the new question.
 await p.evaluate(()=>document.getElementById('next').click());await p.waitForFunction(()=>document.getElementById('study-title').textContent.startsWith('Q002'));assert.equal(await p.locator('#study-input').inputValue(),'');await p.locator('#study-input').fill('第二题草稿');await p.evaluate(()=>document.getElementById('prev').click());await p.waitForFunction(()=>document.getElementById('study-title').textContent.startsWith('Q001'));assert.equal(await p.locator('#study-input').inputValue(),'第一题追问草稿');
 await p.screenshot({path:path.join(__dirname,'preview-sheet-mobile.png')});
 await p.locator('#study-chat-hide').click();await p.locator('#bank-toggle').click();await p.locator('#bank-hot100').click();await p.locator('#hot-ask-ai').click();assert.equal(await p.locator('#hot100-root').isVisible(),true);assert.equal(await p.locator('#study-input').inputValue(),'');assert.match(await p.locator('#study-title').innerText(),/两数之和/);
 await p.locator('#study-input').fill('算法题草稿');await p.evaluate(()=>StudyBack());assert.equal(await p.locator('#study-dialog').isVisible(),false);await p.locator('#hot-ask-ai').click();assert.equal(await p.locator('#study-input').inputValue(),'算法题草稿');
 await p.setViewportSize({width:390,height:550});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const small=await p.locator('#study-dialog').boundingBox();assert.ok(small.height<=235&&small.y+small.height<=550);const inputSmall=await p.locator('#study-input').boundingBox();assert.ok(inputSmall.y-small.y<80);assert.ok(await p.locator('#study-send').isVisible());await p.screenshot({path:path.join(__dirname,'preview-sheet-keyboard.png')});
 assert.deepEqual(errors,[]);console.log('PASS: inline sheet, visible question, expand/collapse preserving input, background stream persistence, per-question draft isolation, bank switching, Android back and small viewport.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
