// Browser tests use a fresh, isolated context; they never touch the user's profile.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {createHash}=require('node:crypto');
(async()=>{
  const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1100}});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const OLD='ai-practice-150-v1',HOT='leetcode-hot100-python-v1';
  const previous={answers:{1:{choice:'B',correct:true},4:{choice:'A',correct:false},93:{choice:'D',correct:true}},saved:[1,4,93],current:93};
  const raw=JSON.stringify(previous);
  await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
  await page.evaluate(({OLD,raw})=>localStorage.setItem(OLD,raw),{OLD,raw});
  await page.reload();
  assert.equal(await page.locator('#doneStat').innerText(),'3');
  assert.equal(await page.locator('#wrongStat').innerText(),'1');
  assert.equal(await page.locator('#savedStat').innerText(),'3');
  assert.equal(await page.locator('#question .qid').innerText(),'Q093');
  assert.equal(await page.evaluate(k=>localStorage.getItem(k),OLD),raw);
  const originalFile=fs.readFileSync(path.join(__dirname,'questions.json'));
  assert.equal(createHash('sha256').update(originalFile).digest('hex'),'5576ad962568d0c55cae4be32fbe86e67c15ebcef24f707d1a79718b25a5e7b3');
  const previousData=JSON.parse(originalFile.toString('utf8'));
  assert.deepEqual(await page.evaluate(()=>JSON.parse(document.getElementById('question-data').textContent)),previousData);
  await page.locator('#bank-toggle').click();await page.locator('#bank-hot100').click();
  assert.equal(await page.locator('#ai-bank-root').isVisible(),false);
  assert.equal(await page.locator('#h-grid button').count(),100);
  assert.equal(await page.locator('#h-topic-nav button').count(),17);
  assert.equal(await page.locator('#h-solution').getAttribute('open'),null);
  assert.match(await page.locator('.hot-title').innerText(),/1. 两数之和/);
  assert.equal(await page.locator('.hot-official').getAttribute('href'),'https://leetcode.cn/problems/two-sum/');
  const draft='def twoSum(nums, target):\n    # 我的草稿：哈希表\n    return [0, 1]\n';
  await page.locator('#h-draft').fill(draft);
  await page.locator('[data-h-mark="review"]').click();
  await page.locator('#h-bookmark').click();
  assert.equal(await page.locator('#h-review-stat').innerText(),'1');
  assert.equal(await page.locator('#h-saved-stat').innerText(),'1');
  assert.equal(await page.locator('#h-draft').inputValue(),draft);
  await page.screenshot({path:path.join(__dirname,'preview-hot100-overview.png'),fullPage:false});
  await page.locator('#h-solution summary').click();
  assert.match(await page.locator('#h-solution').innerText(),/连续追问与参考答案/);
  assert.match(await page.locator('#h-solution code').last().textContent(),/    def twoSum/);
  await page.screenshot({path:path.join(__dirname,'preview-hot100-desktop.png'),fullPage:true});
  await page.locator('#h-solution summary').click();
  await page.locator('#h-next').click();
  assert.equal(await page.locator('#h-draft').inputValue(),'');
  await page.locator('#h-prev').click();assert.equal(await page.locator('#h-draft').inputValue(),draft);
  await page.locator('#bank-toggle').click();await page.locator('#bank-ai').click();assert.equal(await page.locator('#question .qid').innerText(),'Q093');
  assert.equal(await page.evaluate(k=>localStorage.getItem(k),OLD),raw);
  await page.reload();await page.locator('#bank-toggle').click();await page.locator('#bank-hot100').click();
  assert.equal(await page.locator('#h-draft').inputValue(),draft);
  assert.equal(await page.locator('#h-review-stat').innerText(),'1');assert.equal(await page.locator('#h-saved-stat').innerText(),'1');
  await page.locator('[data-h-mode="review"]').click();assert.equal(await page.locator('#h-grid button').count(),1);
  await page.locator('[data-h-mark="mastered"]').click();assert.equal(await page.locator('#h-review-stat').innerText(),'0');assert.equal(await page.locator('#h-mastered').innerText(),'1');
  await page.locator('[data-h-mode="review"]').click();assert.equal(await page.locator('#h-question .empty').count(),1);
  await page.locator('[data-h-mode="saved"]').click();assert.equal(await page.locator('#h-grid button').count(),1);
  await page.locator('#h-bookmark').click();assert.equal(await page.locator('#h-question .empty').count(),1);
  await page.locator('[data-h-mode="all"]').click();
  for(const [difficulty,n] of [['简单',20],['中等',68],['困难',12]]){await page.locator('#h-difficulty').selectOption(difficulty);assert.equal(await page.locator('#h-grid button').count(),n)}
  await page.locator('#h-difficulty').selectOption('');
  await page.locator('#h-topic').selectOption('0');assert.equal(await page.locator('#h-grid button').count(),3);
  await page.locator('#h-status').selectOption('mastered');assert.equal(await page.locator('#h-grid button').count(),1);
  await page.locator('#h-status').selectOption('unmarked');assert.equal(await page.locator('#h-grid button').count(),2);
  await page.locator('[data-h-mode="all"]').click();
  await page.locator('#h-search').fill('lc-146');assert.equal(await page.locator('#h-grid button').count(),1);assert.match(await page.locator('.hot-title').innerText(),/LRU/);
  await page.locator('#h-search').fill('no-matching-problem');assert.equal(await page.locator('#h-question .empty').count(),1);
  await page.locator('#h-clear').click();
  const data=await page.evaluate(()=>JSON.parse(document.getElementById('hot100-data').textContent));
  for(const q of data.questions){
    await page.locator(`[data-h-id="${q.id}"]`).click();
    assert.equal(await page.locator('.hot-title').innerText(),`${q.number}. ${q.title}`);
    const blocks=q.blocks.filter(b=>b.style==='Code Block');
    assert.deepEqual(await page.locator('#h-solution code').allTextContents(),blocks.map(b=>b.text));
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  }
  await page.locator('#h-shuffle').click();assert.equal(await page.locator('#h-grid button').count(),100);
  // Keyboard navigation in the algorithm bank must not operate the hidden original bank.
  await page.locator('body').click({position:{x:5,y:5}});
  await page.keyboard.press('ArrowRight');await page.keyboard.press('A');await page.keyboard.press('Enter');
  assert.equal(await page.evaluate(k=>localStorage.getItem(k),OLD),raw);
  await page.locator('#h-search').fill('两数之和');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(__dirname,'preview-hot100-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('#h-solution summary').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('#h-draft').fill('print("<script>safe</script>")');
  await page.reload();await page.locator('#bank-toggle').click();await page.locator('#bank-hot100').click();assert.equal(await page.locator('#h-draft').inputValue(),'print("<script>safe</script>")');
  assert.equal(await page.evaluate(k=>localStorage.getItem(k),OLD),raw);
  const hotBeforeReset=await page.evaluate(k=>localStorage.getItem(k),HOT);
  // Test the preexisting reset only in this disposable context. It must not touch Hot100.
  await page.locator('#bank-toggle').click();await page.locator('#bank-ai').click();await page.locator('#reset').click();await page.locator('#confirmReset').click();
  assert.equal(await page.evaluate(k=>localStorage.getItem(k),HOT),hotBeforeReset);
  assert.deepEqual(errors,[]);
  console.log('PASS: unchanged original data; exact preservation of original answers/favorites/current across update, bank switches, draft edits, hotkey navigation and reload; 100 problems rendered with exact code; topic/difficulty/status/search/favorites/review/shuffle, mobile layout, isolated reset.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
