const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
 await page.evaluate(()=>localStorage.clear());await page.reload();
 assert.equal(await page.locator('#grid button').count(),150);
 assert.equal(await page.locator('#submit').isDisabled(),true);
 await page.screenshot({path:path.join(__dirname,'preview-desktop.png'),fullPage:true});
 await page.locator('[data-choice="A"]').click();await page.locator('#submit').click();
 assert.equal(await page.locator('#wrongStat').innerText(),'1');
 assert.match(await page.locator('.result').innerText(),/正确答案 B/);
 await page.locator('#bookmark').click();await page.reload();
 assert.equal(await page.locator('#savedStat').innerText(),'1');assert.equal(await page.locator('#doneStat').innerText(),'1');
 await page.locator('[data-mode="wrong"]').click();assert.equal(await page.locator('#grid button').count(),1);
 await page.locator('#retry').click();await page.locator('[data-choice="B"]').click();await page.locator('#submit').click();
 assert.equal(await page.locator('#wrongStat').innerText(),'0');
 await page.locator('[data-mode="all"]').click();await page.locator('[data-id="4"]').click();
 for(const k of ['A','C','D'])await page.locator(`[data-choice="${k}"]`).click();
 await page.locator('#submit').click();assert.match(await page.locator('.result').innerText(),/回答正确/);
 await page.locator('#retry').click();await page.locator('[data-choice="A"]').click();await page.locator('#submit').click();assert.match(await page.locator('.result').innerText(),/再巩固/);
 await page.locator('#search').fill('Q093');assert.equal(await page.locator('#grid button').count(),1);assert.match(await page.locator('pre').innerText(),/    bag.append/);
 await page.locator('#search').fill('no-matching-question');assert.equal(await page.locator('.empty').count(),1);
 await page.locator('#clearFilter').click();await page.locator('#typeFilter').selectOption('多选');assert.equal(await page.locator('#grid button').count(),40);
 await page.locator('#moduleFilter').selectOption('0');assert.equal(await page.locator('#grid button').count(),4);
 await page.locator('#shuffle').click();assert.equal(await page.locator('#grid button').count(),4);
 await page.locator('[data-mode="all"]').click();
 // Render every question, including code and explanation, to detect malformed data/DOM.
 await page.evaluate(()=>{for(const q of QS){state.current=q.id;load();if(document.querySelectorAll('.option').length!==4)throw Error('Options '+q.id);}});
 await page.locator('#reset').click();await page.locator('#cancelReset').click();assert.notEqual(await page.locator('#doneStat').innerText(),'0');
 await page.locator('#reset').click();await page.locator('#confirmReset').click();assert.equal(await page.locator('#doneStat').innerText(),'0');assert.equal(await page.locator('#savedStat').innerText(),'0');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:path.join(__dirname,'preview-mobile.png'),fullPage:true});
 await page.locator('[data-choice="B"]').click();await page.locator('#submit').click();
 assert.match(await page.locator('.result').innerText(),/回答正确/);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 console.log('PASS: 150 question rendering, grading, multi-select exact matching, retry, wrong list, favorites, persistence, search, filters, shuffle, reset, mobile overflow; no browser errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
